#{{ $networkId := readFile "./nodeConfig/aeternity.yaml" | fromYaml | get "fork_management.network_id" }}

repositories:
  - name: aeternity
    url: "git+https://github.com/aeternity/hyperchain-starter-kit.git@charts?ref=master"

releases:
  - name: ae-node
    namespace: {{ $networkId }}
    chart: 'aeternity/ae-node'
    values:
      - './values/ae-node.yaml.gotmpl'

