apiVersion: v1
kind: ConfigMap
metadata:
  name: doge-config
  namespace: {{ .Release.Namespace }}
data:
  dogecoin.conf: |-
    {{- range $key, $val := .Values.dogecoinConf }}
    {{ $key }}={{ $val }}
    {{- end}}
  doge-retriever.sh: |
    #!/bin/bash
    set -euo pipefail
    echo "$(ls -lha)"
    ARCH=$(uname -m)
    echo "PWD: $(pwd)"
    FILENAME=dogecoin-{{ .Chart.AppVersion }}-$ARCH-linux-gnu.tar.gz
    REL_ROOT=https://github.com/dogecoin/dogecoin/releases/download/v{{ .Chart.AppVersion }}/
    URL=$REL_ROOT$FILENAME
    rm app && ln -s ./dogecoin-{{ .Chart.AppVersion }} app
    mkdir -p /home/dogecoin/.dogecoin/ && chown -R 1000:1000 /home/dogecoin/.dogecoin/
    if [ -f "$FILENAME" ]; then
      echo "File $FILENAME already exists. Skipping download."
      exit 0
    else
      apt update && apt install -y curl
      echo "File $FILENAME does not exist. Downloading from $URL."
      curl -o ./$FILENAME $URL
    fi
    echo "Extracting $FILENAME"
    test $? -eq 0 && tar -xxf ./$FILENAME

