apiVersion: v1
kind: Service
metadata:
  name: {{ include "doge.fullname" . }}
  labels:
    {{- include "doge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: http
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.rpcPort }}
      targetPort: http
      protocol: TCP
      name: rpc
  selector:
    {{- include "doge.selectorLabels" . | nindent 4 }}
