faucet:
  account:
    addr: 'ak_2hgkiuwWCkqYkLqCXFrHRMCM5gDfHUJuR5CjEyGg9i8FSNwFVS'
    index: 0
    mnemonic: 'firm video try glory loan casual satoshi health process bar speak universe code kidney merit fortune mom bag must acid business phone prosper security'
    privKey: '3317bc74af273f58e8e03dff5cca7a0ff1ae77a2b4203a95de6880d224f3c120e013c9d04ad5b8dba660d15c110f5bb2fd3cec917ffa161a838f474ccf4c8b95'
  initialBalance: 1000000000000000000000000000
pinners:
  - account:
      addr: 'ak_24aHK5iS3xnP4eu1y168Pm5asPegJ8idVBVEfmBjhCYnMD1cEv'
      index: 0
      mnemonic: 'fly net unable husband resist culture dutch bread main despair crouch enact joke frown across alcohol invest crowd elder plug tobacco excite pottery vast'
      privKey: '67a166b4e0f040f9b1f8d88427be4884ced869c53c65d4ebf4baa0f97f3972cf8bcf95b6562d59d608b5d3f6e9bac066c621e84547dbf739d30a9bd8aba8f18a'
    owner: 'ak_2rrpWFA8c2uVcRnkrm899heZpkdrmCMF7cp9tSoyTUg11NWwav'
  - account:
      addr: 'ak_oQNBpRUJpYSEvbZ71EHzVy1L9PrJXRPqABiXHyPMUuyPJ2naT'
      index: 0
      mnemonic: 'you car dinosaur grape analyst empty wrap clump night forum custom lady dilemma vital hub average tag mammal unfold talk pizza debate deliver notice'
      privKey: 'c5e7dac37efbf7494f7a7fa74c8565d513fb5ea0828a179a6cc9c6e1336c9372695d044dddf87511c916733af95507d0e60f4735659162487adbabedf66c983e'
    owner: 'ak_mP9bNUcF9ky1VKcFTjtnqn2atz5yh6RUciP74WhHZdmRBbG3L'
  - account:
      addr: 'ak_gkTeqnfqmVLgKBXW7L76ftCbHJ56bjXQm9RUxXHTNMsVLK5vf'
      index: 0
      mnemonic: 'flag alert best dragon more egg section obscure problem glove slide stairs govern river harvest wood fish nose mass orphan drama impact robot floor'
      privKey: '3e8746c84fb833588bfded04541c3bba57bd206aba1da89efc325c3dbd55bee75a41727cb62d01e3538dcad6dc341ad68375d846ecee20b94b8fe4b072e35a0c'
    owner: 'ak_jg4B4pJMEKAPemUXvVKp65hfKq1t9Te96kjYG9hRoRRkySEvj'
treasury:
  account:
    addr: 'ak_ZVG2VYYoo3cJq8oz6y7ikpsNhTbEWPXTbNmTmYjcAQPYoi3Qm'
    index: 0
    mnemonic: 'lamp chase catch menu warm champion dust sorry client fine spin arena apart method pumpkin truth fault tide cruel tuna enhance claw clog coast'
    privKey: 'b7aa4b0b07a7e156c24c95a1090323a0406a24aedf265dc609d139d7dd31239749c426f0b569215309ba8797a149243c0c00c3b7668d7b3f2e9e19ec7e668e0c'
  initialBalance: 1000000000000000000000000000000000000000000000000
validators:
  - account:
      addr: 'ak_2rrpWFA8c2uVcRnkrm899heZpkdrmCMF7cp9tSoyTUg11NWwav'
      index: 0
      mnemonic: 'offer sun gentle code mobile behind rather stage theory side this push pulp kit wonder depend gauge indoor cheap shed simple void tackle sport'
      privKey: 'c00b7ed31e67685433d51f41d0c5a6364466e237087e98a4ed5fb907550d1486f4e82d1b2753819bf7b4abd3b843d96885727c37e414c7f65d719fce8c4f7684'
    initialBalance: 3100000000000000000000000000
  - account:
      addr: 'ak_mP9bNUcF9ky1VKcFTjtnqn2atz5yh6RUciP74WhHZdmRBbG3L'
      index: 0
      mnemonic: 'faith town reflect radar critic tattoo sign already fatal layer success rely husband movie pattern crane thumb wheel room patrol critic sausage category shrimp'
      privKey: 'feab25ac1ebe05c0415246c44b12bc81be3d7a0200ef4d6e3f733cf9f4cd2bdc64c6428d2b11080a1c1418439cbfdc1c09f1f4abebbd882137473f2d1a6699cd'
    initialBalance: 3100000000000000000000000000
  - account:
      addr: 'ak_jg4B4pJMEKAPemUXvVKp65hfKq1t9Te96kjYG9hRoRRkySEvj'
      index: 0
      mnemonic: 'zone lizard kangaroo dust desk survey pizza swap miracle mercy kite trim few example actor abuse select alter give gun story divide stereo size'
      privKey: 'ffd169a0b6e0498c2b4861df9aa875924a79cb9b04a4149560ffb979962f1af060e523d22c79e6f926763655ab1560b3b9a1d3ee94238305003d7f714c7e4f8d'
    initialBalance: 3100000000000000000000000000
