apiVersion: v1
kind: ConfigMap
metadata:
  name: data-aecore-iris
data:
  {{ if .Values.accountsJsonOverride }}
  hc2_accounts.json: |
    {{ .Values.accountsJsonOverride | nindent 4 | trim }}
  {{ end }}
  {{ if .Values.contractsJsonOverride }}
  hc2_contracts.json: |
    {{ .Values.contractsJsonOverride | nindent 4 | trim }}
  {{ end }}
