apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-snapshots
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.snapshotsDirClaimSize }}
