apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-snapshots
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.restoreFromSnapshot.snapshotsDirClaimSize }}
